version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "weekly"

  # Monitor GitHub Actions workflows (.github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
