import { Component, input } from '@angular/core';
import {
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleUser,
  Clock,
  Copy,
  Gamepad2,
  ImageOff,
  Inbox,
  Info,
  LayoutDashboard,
  LayoutGrid,
  LucideAngularModule,
  Menu,
  Moon,
  Puzzle,
  RefreshCw,
  Sun,
  Timer,
  Trees,
  Trophy,
  UserRoundCog,
  Users,
} from 'lucide-angular';

const usedIcons = {
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleUser,
  Gamepad2,
  ImageOff,
  Inbox,
  Info,
  LayoutDashboard,
  LayoutGrid,
  Menu,
  Moon,
  Puzzle,
  RefreshCw,
  Sun,
  Trees,
  Trophy,
  UserRoundCog,
  Users,
  Timer,
  CircleCheck,
  Clock,
  Copy,
  ArrowRight,
};

@Component({
  selector: 'app-icon',
  standalone: true,
  providers: [LucideAngularModule.pick(usedIcons).providers!],
  imports: [LucideAngularModule],
  templateUrl: './icon.html',
  styleUrl: './icon.css',
})
export class IconComponent {
  name = input<string>();
}
